### ISSUE TITLE
无法发送邮件

### ISSUE THREAD

**Issue by anyiweb** [byends/CommentToMail#18]
已配置好smtp显示：
Attempt to assign property "from" on null
![image](https://user-images.githubusercontent.com/60560420/170877723-2f7f928e-1b04-4219-ae5f-392077f2b636.png)

**Comment by anyiweb** [comment]
已解决

**Comment by missedmessage** [comment]
怎么解决的？求指教

**Comment by anyiweb** [comment]
> 怎么解决的？求指教

过了太久了，我忘了，应该就是smtp写错了可能
