### ISSUE TITLE
为什么要使用文件存储评论信息呢？

### ISSUE THREAD

**Issue by virusdefender** [byends/CommentToMail#2]
最近大致看了一下插件的源代码，是先把评论写入文件，然后以文件名为 url 参数传递到 action 的。直接把评论的内容格式户成 json 在 url 里面传递不可以么？

很多 php 环境本地都是不可写的，比如各种 app engine，这样就大大的限制了插件的利用场景。

**Comment by byends** [comment]
如果评论内容很少，这确实是一种办法，但若评论内容很多（比如包括较多的富文本）的话，URL传递存在参数过长而被web服务器截断的问题

**Comment by virusdefender** [comment]
那就用 post 啊~

**Comment by byends** [comment]
POST 是可行的。只不过，这里原来的实现机制是为了异步发送邮件。
