### ISSUE TITLE
怎么利用好[支持socket 和 curl 两种方式异步触发请求]

### ISSUE THREAD

**Issue by chakhsu** [byends/CommentToMail#5]
要做一个评论回复邮件提醒的勾选☑️

感觉是需要【支持socket 和 curl 两种方式异步触发请求】这个功能去做的。

能否告诉我一下 怎么写个代码。

**Comment by kokororin** [comment]
可以使用guzzle来发送异步请求

**Comment by byends** [comment]
默认是支持异步请求的，但和服务器有关，有些未开启curl，或者 socket 也不支持，那就无法正常使用。
勾选我记得是支持的，看看代码吧
